# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: 🐛 Bug Report
description: Problems with xview-yolov3
labels: [bug, triage]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an xview-yolov3 🐛 Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/ultralytics/xview-yolov3/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the xview-yolov3 [issues](https://github.com/ultralytics/xview-yolov3/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: Component
      description: |
        Please select the part of the repository where you found the bug.
      multiple: true
      options:
        - "Preprocessing"
        - "Training"
        - "Inference"
        - "Scoring"
        - "Documentation"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please provide as much information as possible. Copy and paste console output and error messages including the _full_ traceback. If necessary, include screenshots for visual elements only.
      placeholder: |
        💡 ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Share the platform and version information relevant to your report.
      placeholder: |
        Please include:
        - OS (e.g., Ubuntu 22.04, macOS 15)
        - Python and PyTorch versions
        - Hardware (e.g., CPU, GPU model)
        - Any other environment details
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        Provide the smallest command or code snippet needed to reproduce the issue. This is referred to by community members as creating a [minimal reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example).
      placeholder: |
        ```bash
        python train.py ...
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/xview-yolov3/pulls) (PR) to help improve xview-yolov3, especially if you know how to fix the issue.
        See the Ultralytics [Contributing Guide](https://docs.ultralytics.com/help/contributing) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
