# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: 📘 xview-yolov3 README
    url: https://github.com/ultralytics/xview-yolov3#readme
    about: Setup, training, and scoring instructions for the xView YOLOv3 challenge code
  - name: 💬 Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: 🎧 Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
  - name: ⌨️ Reddit
    url: https://reddit.com/r/ultralytics
    about: Ask on Ultralytics Subreddit
